export const actionTypes = {
    BEGIN_AJAX_CALL: 'BEGIN_AJAX_CALL',
    AJAX_CALL_ERROR: 'AJAX_CALL_ERROR',
    LOGIN_REQUEST_SUCCESS: 'LOGIN_REQUEST_SUCCESS',
    LOGIN_UPDATE_EDITING_LOGIN: 'LOGIN_UPDATE_EDITING_LOGIN',
    FETCH_SMS_CONFIG_SUCCESS: 'FETCH_SMS_CONFIG_SUCCESS',
    FETCH_MAPPINGS_SUCCESS: 'FETCH_MAPPINGS_SUCCESS'
};
